# A test LoadBalancer service to check that Azure deploys the correct Azure LB

apiVersion: v1
kind: Service
metadata:
  name: test-lb
spec:
  selector:
    app: example
  ports:
    - port: 8080
      targetPort: 7070
  type: LoadBalancer
